Imrpoved geoip scripts.

diff --git a/trunk/dns_scan/country_dist b/trunk/dns_scan/country_dist
--- a/trunk/dns_scan/country_dist
+++ b/trunk/dns_scan/country_dist
@@ -15,6 +15,12 @@ if [ -f $2 ];then
     exit 3
 fi
 
+which geoiplookup >& /dev/null
+if [ $? != 0 ];then
+    echo "geoiplookup required."
+    exit 4
+fi
+
 tempfile=/var/tmp/tempgeofile
 tempfile2=/var/tmp/tempgeofile_uniq
 
