Changes in main scanner.

diff --git a/dns_scan/scanner b/dns_scan/scanner
--- a/dns_scan/scanner
+++ b/dns_scan/scanner
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-if [ "$2" == "" ];then
-    echo "Usage: $0 <ip from> <ip to>"
+if [ "$3" == "" ];then
+    echo "Usage: $0 <ip from> <ip to> <device>"
     exit 1
 fi
 
@@ -15,7 +15,7 @@ DEV=/dev/null
 
 DELAY=5
 OUTFILE=results/results_$1_$2.txt
-NETDEV=eth0
+NETDEV=$3
 
 ifconfig $NETDEV >& $DEV
 if [ $? != 0 ];then
@@ -26,6 +26,22 @@ fi
 if [ -f $OUTFILE ];then
     echo "Output file $OUTFILE exists. Exiting."
     exit 4
+fi
+
+which tshark &> $DEV
+if [ $? != 0 ];then
+    echo "tshark required"
+    exit 5
+fi
+
+if [ ! -f core_scanner ];then
+    echo "Compiling core scanner"
+    which gcc >& $DEV
+    if [ $? != 0 ];then
+    	echo "gcc required."
+    	exit 5
+    fi
+    gcc -Wall -funroll-loops -O3 core_scanner.c -o core_scanner
 fi
 
 slower() {
@@ -50,7 +66,7 @@ echo "Starting scanner"
 echo "Scanner finished"
 
 echo -n "Waiting slow scan packets"
-slower 30
+slower 10
 echo -n "Stopping radar"
 kill -15 $RADAR_PID
 slower 5
